import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [apiRes, setApiRes] = useState('')


  const apiButtonHandler = async () => {
    const response = await fetch("/api/hello")
    const data = await response.json()


    setApiRes(data.name)
  }

  const apiButtonChecker = () => {


    return (
      <div>
        <button onClick={apiButtonHandler}>Click me</button>
      </div>

    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>

        </h1>
        <div className="apiRes" style={{ color: 'red' }}>
          Res = {apiRes}
        </div>

        {apiButtonChecker()}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
